title = "go-sanitize gitleaks config"

[allowlist]
description = "global allow list"
files = []
paths = [
    '''(?i)\.(?:bmp|gif|jpe?g|png|svg|tiff?)$''',
    '''(?i)\.(?:eot|[ot]tf|woff2?)$''',
    '''(?i)\.(?:docx?|xlsx?|pdf|bin|socket|vsidx|v2|suo|wsuo|dll|pdb|exe|gltf)$''',
]
regexes = []
stopwords = []
commits = []

[[rules]]
id = "github-pat"
description = "GitHub personal access token"
regex = '''gh[pous]_[0-9A-Za-z]{36,255}'''
tags = ["github", "token"]
