# Basic dependabot.yml to update gomod and GitHub Actions dependencies

version: 2
updates:
  - package-ecosystem: "gomod"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "weekly"
      # Check for npm updates at 9am UTC (5am EST)
      time: "10:00"
    assignees:
      - "mrz1836"
    # Labels must be created first
    labels:
      - "chore"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "mrz1836"
    labels:
      - "chore"
    open-pull-requests-limit: 10
