gha_enabled: true
branch: master
blocked_dirs: [ ]
draft: false
description: |
  Sweep AI must follow the repository guidelines in .github/AGENTS.md.
rules:
  - "Read .github/AGENTS.md first; it overrides these rules."
  - "Format code with 'go fmt ./...' and 'goimports -w .'"
  - "Lint with 'golangci-lint run' and vet with 'go vet ./...'"
  - "Run 'go test ./...' before committing"
  - "Commit messages use '<type>(<scope>): <short description>'"
  - "PR titles use '[Subsystem] Imperative and concise summary'"
  - "PR descriptions include: What Changed, Why It Was Necessary, Testing Performed, Impact / Risk"
  - "Run 'go mod tidy' after import changes"
  - "Run 'make govulncheck' when dependencies change"
  - "Report vulnerabilities privately following SECURITY.md"
