# ------------------------------------------------------------------------------
#  Clean Runner Cache Workflow
#
#  Purpose: Remove GitHub Actions runner caches when a pull request is closed.
#
#  Triggers: On pull request close events.
#
#  Maintainer: @mrz1836
# ------------------------------------------------------------------------------

name: clean-runner-cache

on:
  pull_request:
    types: [closed]

# Cancel older runs of the same PR if a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  actions: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      ## Install GitHub CLI for cache management
      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      ## Fetch the list of cache keys and delete them
      - name: Cleanup caches
        run: |
          echo "Fetching list of cache keys"
          cacheKeysForPR=$(gh cache list --ref "$BRANCH" --limit 100 --json id,key,ref | jq -r '.[] | select(.ref == env.BRANCH) | .id')

          # Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
              gh cache delete "$cacheKey" || echo "Failed to delete cache $cacheKey"
            done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
