# ------------------------------------------------------------------------------------
#  Release Workflow
#
#  Purpose: Build & publish releases via GoReleaser whenever a semver tag is pushed.
#
#  Triggers: On push of tags that start with "v" (e.g., v1.2.3)
#
#  Maintainer: @mrz1836
# ------------------------------------------------------------------------------------

name: release

env:
  GO111MODULE: on        # explicit, though modern Go enables this by default

on:
  push:
    tags:
      - 'v*'             # run only on tags that start with "v"

permissions:
  contents: read         # restrict default token to read-only

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  goreleaser:
    permissions:
      contents: write     # required to publish releases
    runs-on: ubuntu-latest

    steps:
      # ———————————————————————————————————————————————
      # 1. Check out full history and tags
      # ———————————————————————————————————————————————
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0          # required for changelog generation

      # ———————————————————————————————————————————————
      # 2. Set up Go with a built‑in module and build cache
      # ———————————————————————————————————————————————
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod # single source of truth
          cache: true
          cache-dependency-path: |
            **/go.mod
            **/go.sum

      # ———————————————————————————————————————————————
      # 3. (Optional) Pre‑flight config validation
      # ———————————————————————————————————————————————
      - name: GoReleaser config check
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
        with:
          version: v2.10.2         # pin exact or at least major
          args: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ———————————————————————————————————————————————
      # 4. Build & publish the release
      # ———————————————————————————————————————————————
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
        with:
          version: v2.10.2      # pin exact or at least major (6/20/2025)
          args: release --clean --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ———————————————————————————————————————————————
      # 5. Publish GoDocs
      # ———————————————————————————————————————————————
      - name: Publish GoDocs
        run: make godocs
